[auth]
redirect_uri = "https://localhost:8501/oauth2callback"
cookie_secret = "fP3nqBHh2M0kS68za4X"

[auth.google]
client_id = "xxx"
client_secret = "xxx"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"